export const mockShopifyStore = {
  id: 12345678,
  name: "Auqli Demo Store",
  email: "demo@auqli.live",
  domain: "auqli-demo.myshopify.com",
  myshopify_domain: "auqli-demo.myshopify.com",
  shop_owner: "John Doe",
  plan_name: "shopify_plus",
  plan_display_name: "Shopify Plus",
  currency: "USD",
  country: "US",
  country_name: "United States",
  customer_email: "support@auqli-demo.myshopify.com",
  money_format: "${{amount}}",
  money_with_currency_format: "${{amount}} USD",
  primary_locale: "en",
  created_at: "2023-03-15T12:00:00-04:00",
  updated_at: "2024-04-01T09:30:00-04:00",
  products_count: 245,
  orders_count: 1892,
  has_storefront: true,
  weight_unit: "lb",
  province: "California",
  phone: "+1 (555) 123-4567",
  timezone: "(GMT-05:00) Eastern Time (US & Canada)",
  iana_timezone: "America/New_York",
  force_ssl: true,
  has_discounts: true,
  has_gift_cards: true,
  setup_required: false,
  marketing_sms_consent_enabled_at_checkout: true,
  shop_image: {
    created_at: "2023-03-15T12:00:00-04:00",
    src: "https://cdn.shopify.com/s/files/1/0012/3456/7890/files/store_logo.png",
  },
}
